name: Build Android APK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client-citizen

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'  # Try older Node version
        cache: 'npm'

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'  # Try older Java version

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Clean install dependencies
      run: |
        rm -rf node_modules package-lock.json
        npm install

    - name: Downgrade problematic dependencies
      run: |
        npm install react-native@0.72.6
        npm install @react-native-async-storage/async-storage@1.19.3
        npx expo install --fix

    - name: Install React Navigation dependencies (older versions)
      run: |
        npm install react-native-gesture-handler@2.12.1
        npm install react-native-safe-area-context@4.7.4
        npm install react-native-screens@3.25.0

    - name: Use Turtle CLI instead of EAS
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      run: |
        npm install -g turtle-cli
        turtle setup:android --sdk-version 44.0.0
        turtle build:android --keystore-path <(echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d) --keystore-password "${{ secrets.KEYSTORE_PASSWORD }}" --key-alias "${{ secrets.KEY_ALIAS }}" --key-password "${{ secrets.KEY_PASSWORD }}" --type apk --output ./app-release.apk

    - name: List files to verify APK
      run: ls -la *.apk

    - name: Upload APK to Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: client-citizen/app-release.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}