name: Build Android APK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client-citizen

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install dependencies
      run: npm install

    - name: Install React Navigation dependencies
      run: npx expo install react-native-gesture-handler react-native-safe-area-context react-native-screens

    - name: Fix Android resource conflicts
      run: |
        # Create a more aggressive fix for the duplicate resource issue
        cat >> android/app/build.gradle << 'EOF'

        android {
            packagingOptions {
                pickFirst "**/libc++_shared.so"
                pickFirst "**/libjsc.so"
            }
        }

        configurations.all {
            exclude group: 'com.google.android.material', module: 'material'
            exclude group: 'androidx.appcompat', module: 'appcompat'
            resolutionStrategy {
                force 'androidx.appcompat:appcompat:1.6.1'
            }
        }
        EOF

    - name: Clean build directories
      run: |
        cd android
        ./gradlew clean

    - name: Build Android APK
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      run: |
        npx expo install --fix
        npx eas build --profile preview --platform android --local --non-interactive --output=./app-release.apk

    - name: List files to verify APK
      run: ls -la *.apk

    - name: Upload APK to Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: client-citizen/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
